# Generated by Django 5.2.8 on 2025-12-01 19:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escrows", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="escrow",
            name="agreement_upload",
            field=models.FileField(blank=True, null=True, upload_to="agreements/"),
        ),
        migrations.AddField(
            model_name="escrow",
            name="broker_a_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="escrow",
            name="broker_a_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="escrow",
            name="broker_b_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="escrow",
            name="broker_b_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="escrow",
            name="closing_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="escrow",
            name="commission_payer",
            field=models.CharField(
                blank=True,
                choices=[("BUYER", "Buyer"), ("SELLER", "Seller"), ("BOTH", "Both")],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="escrow",
            name="commission_payment_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="escrow",
            name="commission_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="escrow",
            name="currency",
            field=models.CharField(
                choices=[("USD", "USD"), ("MXN", "MXN")], default="USD", max_length=5
            ),
        ),
        migrations.AddField(
            model_name="escrow",
            name="due_diligence_days",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="escrow",
            name="due_diligence_deadline",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="escrow",
            name="due_diligence_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="escrow",
            name="due_diligence_scope",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="escrow",
            name="hidden_defects_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="escrow",
            name="participant_role",
            field=models.CharField(
                choices=[
                    ("BUYER", "Buyer"),
                    ("SELLER", "Seller"),
                    ("BROKER", "Broker"),
                ],
                default="BUYER",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="escrow",
            name="property_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="escrow",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("HOUSE", "Casa"),
                    ("APARTMENT", "Departamento"),
                    ("LAND", "Terreno"),
                    ("COMMERCIAL", "Local comercial"),
                    ("OFFICE", "Oficina"),
                ],
                default="HOUSE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="escrow",
            name="property_value",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="escrow",
            name="resolution_days",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="escrow",
            name="responsible_party",
            field=models.CharField(
                blank=True,
                choices=[("BUYER", "Buyer"), ("SELLER", "Seller"), ("BOTH", "Both")],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="escrow",
            name="retention_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="escrow",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("COMMISSION", "Comisión inmobiliaria"),
                    ("DUE_DILIGENCE", "Due diligence"),
                    ("HIDDEN_DEFECTS", "Vicios ocultos"),
                ],
                default="COMMISSION",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="party",
            name="role",
            field=models.CharField(
                choices=[
                    ("BUYER", "Buyer"),
                    ("SELLER", "Seller"),
                    ("BROKER", "Broker"),
                ],
                max_length=20,
            ),
        ),
    ]
